-- ============================================================================
-- Live Class Course Registration System — schema.sql
-- Target: PostgreSQL 16
-- spring.sql.init.mode=always로 매 부트 적용, ddl-auto=validate로 drift 검출
-- ============================================================================

-- 부트마다 멱등 재실행을 위한 DROP. CREATE만으로는 컬럼 변경이 반영되지 않는다.
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- classes
-- ---------------------------------------------------------------------------
CREATE TABLE classes (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id    BIGINT         NOT NULL,
    title         VARCHAR(200)   NOT NULL,
    description   TEXT,
    price         NUMERIC(12, 2) NOT NULL,
    capacity      INT            NOT NULL,
    current_count INT            NOT NULL DEFAULT 0,
    start_date    DATE           NOT NULL,
    end_date      DATE           NOT NULL,
    status        VARCHAR(16)    NOT NULL DEFAULT 'DRAFT',
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_classes_creator
        FOREIGN KEY (creator_id) REFERENCES users(id),
    CONSTRAINT ck_classes_capacity_positive
        CHECK (capacity > 0),
    CONSTRAINT ck_classes_current_count_range
        CHECK (current_count >= 0 AND current_count <= capacity),
    CONSTRAINT ck_classes_date_order
        CHECK (end_date >= start_date),
    CONSTRAINT ck_classes_status
        CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED')),
    CONSTRAINT ck_classes_price_non_negative
        CHECK (price >= 0)
);

CREATE INDEX idx_classes_status ON classes (status);
CREATE INDEX idx_classes_creator_id ON classes (creator_id);

-- ---------------------------------------------------------------------------
-- enrollments
-- ---------------------------------------------------------------------------
CREATE TABLE enrollments (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    class_id      BIGINT      NOT NULL,
    status        VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_at  TIMESTAMPTZ,
    cancelled_at  TIMESTAMPTZ,
    CONSTRAINT fk_enrollments_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_enrollments_class
        FOREIGN KEY (class_id) REFERENCES classes(id),
    CONSTRAINT ck_enrollments_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    -- 상태 ↔ 타임스탬프 정합성
    CONSTRAINT ck_enrollments_confirmed_ts
        CHECK (
            (status = 'CONFIRMED' AND confirmed_at IS NOT NULL)
         OR (status IN ('PENDING', 'CANCELLED'))
        ),
    CONSTRAINT ck_enrollments_cancelled_ts
        CHECK (
            (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
         OR (status IN ('PENDING', 'CONFIRMED'))
        )
);

-- 활성(PENDING/CONFIRMED) enrollment의 (user, class) 유일성
CREATE UNIQUE INDEX uk_active_enrollment
    ON enrollments (user_id, class_id)
    WHERE status <> 'CANCELLED';

-- 사용자별 신청 이력 페이지네이션 가속
CREATE INDEX idx_enrollments_user_created_at
    ON enrollments (user_id, created_at DESC);

CREATE INDEX idx_enrollments_class_id
    ON enrollments (class_id);
