-- 부하 테스트용 사용자 시드 — 멱등.
--   id 1        : creator (강의 생성자)
--   id 2..501   : learner (수강 신청자)
-- generate_series로 500명 시드. S3는 VU=100 환경에서도 동일 사용자 ID 풀을 공유한다.
-- 정원·중복 동시성 검증의 안정성을 위해 사용자 풀을 넉넉히 잡는다.

INSERT INTO users (id, name, email)
VALUES (1, 'creator', 'creator@test.local')
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, name, email)
SELECT n, 'learner-' || n, 'learner-' || n || '@test.local'
FROM generate_series(2, 501) AS n
ON CONFLICT (email) DO NOTHING;

-- GENERATED BY DEFAULT AS IDENTITY는 명시 id 삽입 후 시퀀스를 자동 sync 하지 않는다.
-- 이후 정상 강의·기타 INSERT가 충돌하지 않도록 시퀀스를 현재 MAX(id) 이상으로 끌어올린다.
SELECT setval(
  pg_get_serial_sequence('users', 'id'),
  GREATEST((SELECT MAX(id) FROM users), 501)
);
